# Generated by Django 4.2.6 on 2023-10-29 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='avatar',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='name',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='bio',
            field=models.CharField(max_length=20),
        ),
    ]
