# Generated by Django 4.2.6 on 2023-10-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0002_profileuser_avatar_profileuser_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
