# Generated by Django 4.2.6 on 2023-12-06 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myprofile', '0003_alter_profileuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
