# Generated by Django 4.2.6 on 2023-10-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('genres', models.JSONField(blank=True, null=True)),
                ('characters', models.JSONField(blank=True, null=True)),
                ('edition', models.CharField(blank=True, max_length=100, null=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=100, null=True)),
                ('awards', models.JSONField(blank=True, null=True)),
                ('numRatings', models.IntegerField(blank=True, null=True)),
                ('numLikes', models.IntegerField(blank=True, null=True)),
                ('coverImg', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
