# Generated by Django 4.2.6 on 2023-10-23 15:42

from django.db import migrations
from django.core.management import call_command
import os


def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "homepage\\fixtures\\riviu_buku_books.json", database=schema_editor.connection.alias)

class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]