# Generated by Django 4.2.6 on 2023-10-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
        ('homepage', '0002_load_fixtures'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='review',
            field=models.ManyToManyField(to='review.review'),
        ),
    ]
