# Generated by Django 4.2.6 on 2023-10-29 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_book_liked_by_users'),
        ('homepage', '0003_book_review'),
    ]

    operations = [
    ]
