# Generated by Django 5.0 on 2023-12-11 17:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='coverImg',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
